package vdscratchy.sulfurbox.gui;

import com.google.common.collect.Lists;
import org.jdesktop.beansbinding.*;
import vdscratchy.core.datatypes.Version;
import vdscratchy.sulfurbox.construct.GenerateAll;
import vdscratchy.sulfurbox.data.types.*;
import vdscratchy.sulfurbox.handlers.CurrentProjectHandler;
import vdscratchy.core.validation.ValidationError;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Map;
import java.util.Properties;

/**
 * SulfurBox - vdscratchy.sulfurbox.gui.SulfurBoxGui
 *
 * @author Brandon3055, Vinyl Darkscratch, Covers1624
 * @version 0.0.1
 * @since 0.0.1
 *
 * This is the base code for the project's GUI.  It interacts with the various handlers, primarily the
 * {@link vdscratchy.sulfurbox.handlers.CurrentProjectHandler}, to create the core of the program.  It is advised to
 * avoid modifying any of the code in this class, aside from the event handlers, as they are generated by NetBeans.
 *
 * @see vdscratchy.sulfurbox.handlers.CurrentProjectHandler
 * @see vdscratchy.sulfurbox.data.Mod
 */
public class SulfurBoxGui extends javax.swing.JFrame {

	private Properties properties = new Properties();
	private CurrentProjectHandler currentProject = new CurrentProjectHandler();
	private Color invalidTextFieldInputColor;
	private Color warningTextFieldInputColor;
	private Color invalidChoiceInputColor;
	private Color warningChoiceInputColor;

	private static final int CTRLCMD = Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();

	/**
	 * Creates new form SulfurBoxGui
	 */
	public SulfurBoxGui() {
		System.setProperty("apple.laf.useScreenMenuBar", "true"); // Needed for macOS

		loadProperties();
		initComponents();
		initLAFMenu();
        initTablesListeners();
		pack();

        reloadTables();
	}

	// TODO: Create a proper global properties handler
	private void loadProperties() {
		try {
			File propertyFile = new File("properties");
			if (propertyFile.createNewFile()) properties.load(new FileInputStream(propertyFile));
		} catch (IOException e) {
			throw new RuntimeException(e);
		}

		try {
			UIManager.setLookAndFeel(properties.getProperty("laf", "com.bulenkov.darcula.DarculaLaf"));
			initColors();
			SwingUtilities.updateComponentTreeUI(SulfurBoxGui.this);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void initColors() {
		invalidTextFieldInputColor = new Color((int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("TextField.background").getRed() * 2.0, 255.0))),
				(int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("TextField.background").getGreen() * 0.8, 255.0))),
				(int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("TextField.background").getBlue() * 0.8, 255.0))),
				UIManager.getDefaults().getColor("TextField.background").getAlpha());

		invalidChoiceInputColor = new Color((int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("ComboBox.background").getRed() * 2.0, 255.0))),
				(int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("ComboBox.background").getGreen() * 0.8, 255.0))),
				(int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("ComboBox.background").getBlue() * 0.8, 255.0))),
				UIManager.getDefaults().getColor("ComboBox.background").getAlpha());

		warningTextFieldInputColor = new Color((int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("TextField.background").getRed() * 2.0, 255.0))),
				(int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("TextField.background").getGreen() * 1.6, 255.0))),
				(int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("TextField.background").getBlue() * 0.8, 255.0))),
				UIManager.getDefaults().getColor("TextField.background").getAlpha());

		warningChoiceInputColor = new Color((int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("ComboBox.background").getRed() * 2.0, 255.0))),
				(int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("ComboBox.background").getGreen() * 1.6, 255.0))),
				(int)(Math.max(0.0, Math.min(UIManager.getDefaults().getColor("ComboBox.background").getBlue() * 0.8, 255.0))),
				UIManager.getDefaults().getColor("ComboBox.background").getAlpha());
	}

	/**
	 * This is done runtime rather then hard coded into the gui so that it can support all installed LAF's including OS dependent LAF's
	 * ps. LAF = LookAndFeel
	 */
	private void initLAFMenu() {
		ButtonGroup btnGroup = new ButtonGroup();

		for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
			JRadioButtonMenuItem laf = new JRadioButtonMenuItem(info.getName());
			btnGroup.add(laf);
			lafMenu.add(laf);

			if (UIManager.getLookAndFeel().getName().equals(info.getName())) {
				laf.setSelected(true);
			}

			laf.addActionListener(event -> {
				try {
					properties.setProperty("laf", info.getClassName());
					properties.store(new FileOutputStream("properties"), "Props //TODO create a proper global properties file");

					UIManager.setLookAndFeel(info.getClassName());
					initColors();
					SwingUtilities.updateComponentTreeUI(SulfurBoxGui.this);
					if (info.getName().equals("Metal")) {
						JOptionPane.showMessageDialog(SulfurBoxGui.this, "A restart may be required to correctly apply this change.", "Info", JOptionPane.INFORMATION_MESSAGE);
					}
				}
				catch (Exception e) {
					e.printStackTrace();
					JOptionPane.showMessageDialog(SulfurBoxGui.this, "Something when wrong while setting new look and feel!\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
				}
			});
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        modPropertyTabs = new JTabbedPane();
        modPanel = new JPanel();
        modNameLabel = new JLabel();
        modNameField = new JTextField();
        modPackageLabel = new JLabel();
        modPackageField = new JTextField();
        modPackageSeparatorLabel = new JLabel();
        modPackageMemberField = new JTextField();
        modVersionLabel = new JLabel();
        modVersionField = new JTextField();
        mcForgeVersionLabel = new JLabel();
        mcVersionSelect = new JComboBox<>();
        forgeVersionSelect = new JComboBox<>();
        modDescriptionLabel = new JLabel();
        modDescriptionScrlPane = new JScrollPane();
        modDescriptionField = new JTextArea();
        modHomePageLabel = new JLabel();
        modHomePageHttpsSelect = new JComboBox<>();
        modHomePageField = new JTextField();
        modRepoLabel = new JLabel();
        modRepoField = new JTextField();
        issueTrackerLabel = new JLabel();
        issueTrackerField = new JTextField();
        modUpdateChecksLabel = new JLabel();
        modUpdateChecksField = new JTextField();
        modCurseIDLabel = new JLabel();
        modCurseIDField = new JTextField();
        modLicenseLabel = new JLabel();
        modLicenseField = new JComboBox<>();
        modLogoLabel = new JLabel();
        modLogoField = new JTextField();
        modLogoBrowseButton = new JButton();
        attribPanel = new JPanel();
        attribContributorScrlPane = new JScrollPane();
        attribContributorTable = new JTable();
        attribContributorAdd = new JButton();
        attribContributorRemove = new JButton();
        attribCreditsLabel = new JLabel();
        attribCreditsScrlPane = new JScrollPane();
        attribCreditsField = new JTextArea();
        depPanel = new JPanel();
        depParentLabel = new JLabel();
        depParentCheck = new JCheckBox();
        depParentField = new JTextField();
        depModsPanel = new JPanel();
        depModsLabel = new JLabel();
        depModsAdd = new JButton();
        depModsRemove = new JButton();
        depModsScrlPane = new JScrollPane();
        depModsTable = new JTable();
        depJavaLibsPanel = new JPanel();
        depJavaLibsFields = new JLabel();
        depJavaLibsAdd = new JButton();
        depJavaLibsRemove = new JButton();
        depModsScrlPane1 = new JScrollPane();
        depJavaLibsTable = new JTable();
        depMavenRepsPanel = new JPanel();
        depMavenRepsLabel = new JLabel();
        depMavenRepsAdd = new JButton();
        depMavenRepsRemove = new JButton();
        depModsScrlPane3 = new JScrollPane();
        depMavenRepsTable = new JTable();
        depManifestPanel = new JPanel();
        depManifestLabel = new JLabel();
        depManifestAdd = new JButton();
        depManifestRemove = new JButton();
        depModsScrlPane2 = new JScrollPane();
        depManifestTable = new JTable();
        intellijRadButton = new JRadioButton();
        eclipseRadButton = new JRadioButton();
        gradleVersionLabel = new JLabel();
        javaVersionLabel = new JLabel();
        modGeneratePanel = new JPanel();
        modGenerateButton = new JButton();
        filler1 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(32767, 0));
        filler2 = new Box.Filler(new Dimension(0, 0), new Dimension(0, 0), new Dimension(32767, 0));
        menuBar = new JMenuBar();
        fileMenu = new JMenu();
        menuItemNew = new JMenuItem();
        menuItemOpen = new JMenuItem();
        menuItemSave = new JMenuItem();
        menuItemSaveAs = new JMenuItem();
        editMenu = new JMenu();
        menuItemCopy = new JMenuItem();
        menuItemCut = new JMenuItem();
        menuItemPaste = new JMenuItem();
        menuItemSelectAll = new JMenuItem();
        menuItemDeselect = new JMenuItem();
        projectMenu = new JMenu();
        menuItemGenerate = new JMenuItem();
        menuItemClean = new JMenuItem();
        menuItemCompileJar = new JMenuItem();
        aboutMenu = new JMenu();
        menuItemAboutSB = new JMenuItem();
        menuItemManual = new JMenuItem();
        menuItemOnlineSupport = new JMenuItem();
        menuItemCheckUpdates = new JMenuItem();
        menuItemRequestRepo = new JMenuItem();
        optionsMenu = new JMenu();
        lafMenu = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("SulfurBox");
        setMinimumSize(new Dimension(400, 690));

        modPanel.setBorder(BorderFactory.createEtchedBorder());

        modNameLabel.setText("Name");

        modNameField.setText("Test Mod");
        modNameField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modNameFieldKeyReleased(evt);
            }
        });

        modPackageLabel.setText("Package");

        modPackageField.setText("mods.badhandwriting.org");
        modPackageField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modPackageFieldKeyReleased(evt);
            }
        });

        modPackageSeparatorLabel.setText(".");

        modPackageMemberField.setText("testmod");
        modPackageMemberField.setMaximumSize(new Dimension(73, 24));
        modPackageMemberField.setMinimumSize(new Dimension(73, 24));
        modPackageMemberField.setName(""); // NOI18N
        modPackageMemberField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modPackageMemberFieldKeyReleased(evt);
            }
        });

        modVersionLabel.setText("Version");

        modVersionField.setText("0.0.1.# - DEV");
        modVersionField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modVersionFieldKeyReleased(evt);
            }
        });

        mcForgeVersionLabel.setText("Forge Version");

        mcVersionSelect.setModel(new DefaultComboBoxModel<>(new String[] { "MC 1.11.2" }));
        mcVersionSelect.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                mcVersionSelectItemStateChanged(evt);
            }
        });

        forgeVersionSelect.setModel(new DefaultComboBoxModel<>(new String[] { "13.20.10.2228 - Recommended" }));
        forgeVersionSelect.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                forgeVersionSelectItemStateChanged(evt);
            }
        });

        modDescriptionLabel.setText("Description");

        modDescriptionField.setColumns(20);
        modDescriptionField.setRows(5);
        modDescriptionField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modDescriptionFieldKeyReleased(evt);
            }
        });
        modDescriptionScrlPane.setViewportView(modDescriptionField);

        modHomePageLabel.setText("Home Page");

        modHomePageHttpsSelect.setModel(new DefaultComboBoxModel<>(new String[] { "https://", "http://" }));
        modHomePageHttpsSelect.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                modHomePageHttpsSelectItemStateChanged(evt);
            }
        });

        modHomePageField.setText("www.???.org");
        modHomePageField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modHomePageFieldKeyReleased(evt);
            }
        });

        modRepoLabel.setText("Repository");

        modRepoField.setText("https://github.com/brandon3055/Draconic-Evolution");
        modRepoField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modRepoFieldKeyReleased(evt);
            }
        });

        issueTrackerLabel.setText("Issue Tracker");

        issueTrackerField.setText("https://github.com/brandon3055/Draconic-Evolution/issues");
        issueTrackerField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                issueTrackerFieldKeyReleased(evt);
            }
        });

        modUpdateChecksLabel.setText("Update Checks");

        modUpdateChecksField.setText("www.blablabla.com/stuff");
        modUpdateChecksField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modUpdateChecksFieldKeyReleased(evt);
            }
        });

        modCurseIDLabel.setText("CurseForge ID");

        modCurseIDField.setText("907694083706973409786");
        modCurseIDField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modCurseIDFieldKeyReleased(evt);
            }
        });

        modLicenseLabel.setText("License");

        modLicenseField.setEditable(true);
        modLicenseField.setModel(new DefaultComboBoxModel<>(new String[] { "GNU GPL V3.0" }));
        modLicenseField.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent evt) {
                modLicenseFieldItemStateChanged(evt);
            }
        });
        modLicenseField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modLicenseFieldKeyReleased(evt);
            }
        });

        modLogoLabel.setText("Logo File");

        modLogoField.setText("resources/textures/logo.png");
        modLogoField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                modLogoFieldKeyReleased(evt);
            }
        });

        modLogoBrowseButton.setText("Browse");
        modLogoBrowseButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                modLogoBrowseButtonActionPerformed(evt);
            }
        });

        GroupLayout modPanelLayout = new GroupLayout(modPanel);
        modPanel.setLayout(modPanelLayout);
        modPanelLayout.setHorizontalGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(modPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(modUpdateChecksLabel)
                    .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent(modLogoLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modLicenseLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modCurseIDLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                        .addComponent(modDescriptionLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modVersionLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modPackageLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modNameLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mcForgeVersionLabel, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(modRepoLabel, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modHomePageLabel, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueTrackerLabel))
                .addGap(18, 18, 18)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(modRepoField, GroupLayout.Alignment.TRAILING)
                    .addGroup(modPanelLayout.createSequentialGroup()
                        .addComponent(modPackageField)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modPackageSeparatorLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modPackageMemberField, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE))
                    .addComponent(modNameField)
                    .addComponent(modVersionField)
                    .addGroup(modPanelLayout.createSequentialGroup()
                        .addComponent(mcVersionSelect, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(forgeVersionSelect, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(modDescriptionScrlPane)
                    .addComponent(modUpdateChecksField)
                    .addComponent(modCurseIDField)
                    .addComponent(modLicenseField, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(modPanelLayout.createSequentialGroup()
                        .addComponent(modLogoField)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modLogoBrowseButton))
                    .addGroup(modPanelLayout.createSequentialGroup()
                        .addComponent(modHomePageHttpsSelect, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modHomePageField))
                    .addComponent(issueTrackerField, GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                .addContainerGap())
        );
        modPanelLayout.setVerticalGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(modPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modNameLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modPackageField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modPackageSeparatorLabel)
                    .addComponent(modPackageMemberField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modPackageLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modVersionField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modVersionLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(mcVersionSelect, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgeVersionSelect, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcForgeVersionLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(modDescriptionLabel)
                    .addComponent(modDescriptionScrlPane, GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modHomePageField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modHomePageHttpsSelect, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modHomePageLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modRepoField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modRepoLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(issueTrackerField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueTrackerLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modUpdateChecksField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modUpdateChecksLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modCurseIDField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modCurseIDLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modLicenseField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modLicenseLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(modLogoLabel)
                    .addComponent(modLogoField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(modLogoBrowseButton))
                .addGap(16, 16, 16))
        );

        modPropertyTabs.addTab("Mod Info", modPanel);

        attribContributorTable.setModel(contribTableModel = new DefaultTableModel(
            new String [] {
                "", "Name", "Username", "Role"
            },0
        )
        {
            Class[] types = new Class [] {
                Boolean.class, String.class, String.class
            };

            public Class getColumnClass(int column) {
                Object c = getValueAt(0, column);
                return c == null ? String.class : c.getClass();
            }
        });
        attribContributorTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        attribContributorTable.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                attribContributorTableKeyReleased(evt);
            }
        });
        attribContributorScrlPane.setViewportView(attribContributorTable);
        //Adds the ComboBox editor to the Role column
        TableColumn roleColumn = attribContributorTable.getColumnModel().getColumn(3);
        JComboBox<String> comboBox = new JComboBox<>();
        Author.ALL_ROLES.forEach(comboBox::addItem);
        roleColumn.setCellEditor(new DefaultCellEditor(comboBox));
        //Applies a custom cell renderer with
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        roleColumn.setCellRenderer(centerRenderer);

        attribContributorAdd.setText("+");
        attribContributorAdd.setToolTipText("Add Contributor");
        attribContributorAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                attribContributorAddActionPerformed(evt);
            }
        });

        attribContributorRemove.setText("x");
        attribContributorRemove.setToolTipText("Remove Selected");
        attribContributorRemove.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                attribContributorRemoveActionPerformed(evt);
            }
        });

        attribCreditsLabel.setText("Credits");

        attribCreditsField.setColumns(20);
        attribCreditsField.setRows(5);
        attribCreditsField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                attribCreditsFieldKeyReleased(evt);
            }
        });
        attribCreditsScrlPane.setViewportView(attribCreditsField);

        GroupLayout attribPanelLayout = new GroupLayout(attribPanel);
        attribPanel.setLayout(attribPanelLayout);
        attribPanelLayout.setHorizontalGroup(attribPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(attribPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attribPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(attribCreditsScrlPane)
                    .addGroup(attribPanelLayout.createSequentialGroup()
                        .addComponent(attribCreditsLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attribContributorAdd)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attribContributorRemove))
                    .addComponent(attribContributorScrlPane, GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE))
                .addContainerGap())
        );
        attribPanelLayout.setVerticalGroup(attribPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(attribPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attribContributorScrlPane, GroupLayout.PREFERRED_SIZE, 350, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(attribPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(attribContributorRemove, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribContributorAdd, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                    .addComponent(attribCreditsLabel))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attribCreditsScrlPane, GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        modPropertyTabs.addTab("Attribution", attribPanel);

        depPanel.setBorder(BorderFactory.createEtchedBorder());

        depParentLabel.setText("Parent Mod");

        depParentCheck.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                depParentCheckStateChanged(evt);
            }
        });

        Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, depParentCheck, ELProperty.create("${selected}"), depParentField, BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        depParentField.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                depParentFieldKeyReleased(evt);
            }
        });

        depModsPanel.setBorder(BorderFactory.createEtchedBorder());

        depModsLabel.setText("Mod Dependencies");

        depModsAdd.setText("+");
        depModsAdd.setToolTipText("Add New");
        depModsAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depModsAddActionPerformed(evt);
            }
        });

        depModsRemove.setText("x");
        depModsRemove.setToolTipText("Remove Selected");
        depModsRemove.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depModsRemoveActionPerformed(evt);
            }
        });

        depModsTable.setModel(depModsTableModel = new DefaultTableModel(
            new String [] {"Mod Name", "Required Version", "Max Version"}, 0
        ) {
            Class[] types = new Class [] {
                String.class, String.class, Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        depModsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        depModsTable.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                depModsTableKeyReleased(evt);
            }
        });
        depModsScrlPane.setViewportView(depModsTable);
        if (depModsTable.getColumnModel().getColumnCount() > 0) {
            depModsTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            depModsTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        GroupLayout depModsPanelLayout = new GroupLayout(depModsPanel);
        depModsPanel.setLayout(depModsPanelLayout);
        depModsPanelLayout.setHorizontalGroup(depModsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depModsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depModsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depModsScrlPane, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, depModsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(depModsAdd)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depModsRemove))
                    .addComponent(depModsLabel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        depModsPanelLayout.setVerticalGroup(depModsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depModsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depModsLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depModsScrlPane, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depModsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(depModsRemove, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                    .addComponent(depModsAdd, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        depJavaLibsPanel.setBorder(BorderFactory.createEtchedBorder());

        depJavaLibsFields.setText("Java Dependencies");

        depJavaLibsAdd.setText("+");
        depJavaLibsAdd.setToolTipText("Add New");
        depJavaLibsAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depJavaLibsAddActionPerformed(evt);
            }
        });

        depJavaLibsRemove.setText("x");
        depJavaLibsRemove.setToolTipText("Remove Selected");
        depJavaLibsRemove.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depJavaLibsRemoveActionPerformed(evt);
            }
        });

        depJavaLibsTable.setModel(depJavaLibsTableModel = new DefaultTableModel(
            new String [] {"Name", "Required Version", "Max Version"}, 0
        ) {
            Class[] types = new Class [] {
                String.class, String.class, Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        depJavaLibsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        depJavaLibsTable.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                depJavaLibsTableKeyReleased(evt);
            }
        });
        depModsScrlPane1.setViewportView(depJavaLibsTable);
        if (depJavaLibsTable.getColumnModel().getColumnCount() > 0) {
            depJavaLibsTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            depJavaLibsTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        GroupLayout depJavaLibsPanelLayout = new GroupLayout(depJavaLibsPanel);
        depJavaLibsPanel.setLayout(depJavaLibsPanelLayout);
        depJavaLibsPanelLayout.setHorizontalGroup(depJavaLibsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depJavaLibsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depJavaLibsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depJavaLibsFields, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, depJavaLibsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(depJavaLibsAdd)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depJavaLibsRemove))
                    .addComponent(depModsScrlPane1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap())
        );
        depJavaLibsPanelLayout.setVerticalGroup(depJavaLibsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depJavaLibsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depJavaLibsFields)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depModsScrlPane1, GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depJavaLibsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(depJavaLibsRemove, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                    .addComponent(depJavaLibsAdd, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        depMavenRepsPanel.setBorder(BorderFactory.createEtchedBorder());

        depMavenRepsLabel.setText("Maven Repositories");

        depMavenRepsAdd.setText("+");
        depMavenRepsAdd.setToolTipText("Add New");
        depMavenRepsAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depMavenRepsAddActionPerformed(evt);
            }
        });

        depMavenRepsRemove.setText("x");
        depMavenRepsRemove.setToolTipText("Remove Selected");
        depMavenRepsRemove.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depMavenRepsRemoveActionPerformed(evt);
            }
        });

        depMavenRepsTable.setModel(depMavenRepsTableModel = new DefaultTableModel(
            new String [] {"Repo Name", "URL"}, 0
        ) {
            Class[] types = new Class [] {
                String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        depMavenRepsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        depMavenRepsTable.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                depMavenRepsTableKeyReleased(evt);
            }
        });
        depModsScrlPane3.setViewportView(depMavenRepsTable);
        if (depMavenRepsTable.getColumnModel().getColumnCount() > 0) {
            depMavenRepsTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            depMavenRepsTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        GroupLayout depMavenRepsPanelLayout = new GroupLayout(depMavenRepsPanel);
        depMavenRepsPanel.setLayout(depMavenRepsPanelLayout);
        depMavenRepsPanelLayout.setHorizontalGroup(depMavenRepsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depMavenRepsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depMavenRepsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depModsScrlPane3, GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(depMavenRepsLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, depMavenRepsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(depMavenRepsAdd)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depMavenRepsRemove)))
                .addContainerGap())
        );
        depMavenRepsPanelLayout.setVerticalGroup(depMavenRepsPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depMavenRepsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depMavenRepsLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depModsScrlPane3, GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depMavenRepsPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(depMavenRepsRemove, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                    .addComponent(depMavenRepsAdd, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        depManifestPanel.setBorder(BorderFactory.createEtchedBorder());

        depManifestLabel.setText("Manifest");

        depManifestAdd.setText("+");
        depManifestAdd.setToolTipText("Add New");
        depManifestAdd.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depManifestAddActionPerformed(evt);
            }
        });

        depManifestRemove.setText("x");
        depManifestRemove.setToolTipText("Remove Selected");
        depManifestRemove.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                depManifestRemoveActionPerformed(evt);
            }
        });

        depManifestTable.setModel(depManifestTableModel = new DefaultTableModel(
            new String [] {"Key", "Value"}, 0
        ) {
            Class[] types = new Class [] {
                String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        depManifestTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        depManifestTable.addKeyListener(new KeyAdapter() {
            public void keyReleased(KeyEvent evt) {
                depManifestTableKeyReleased(evt);
            }
        });
        depModsScrlPane2.setViewportView(depManifestTable);
        if (depManifestTable.getColumnModel().getColumnCount() > 0) {
            depManifestTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            depManifestTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        }

        GroupLayout depManifestPanelLayout = new GroupLayout(depManifestPanel);
        depManifestPanel.setLayout(depManifestPanelLayout);
        depManifestPanelLayout.setHorizontalGroup(depManifestPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depManifestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depManifestPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depManifestLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, depManifestPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(depManifestAdd)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depManifestRemove))
                    .addComponent(depModsScrlPane2, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        depManifestPanelLayout.setVerticalGroup(depManifestPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depManifestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depManifestLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depModsScrlPane2, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depManifestPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(depManifestRemove, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE)
                    .addComponent(depManifestAdd, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        GroupLayout depPanelLayout = new GroupLayout(depPanel);
        depPanel.setLayout(depPanelLayout);
        depPanelLayout.setHorizontalGroup(depPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depParentLabel)
                .addGap(34, 34, 34)
                .addComponent(depParentCheck)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depParentField)
                .addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, depPanelLayout.createSequentialGroup()
                .addGroup(depPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depMavenRepsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depModsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depManifestPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depJavaLibsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        depPanelLayout.setVerticalGroup(depPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(depPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depParentCheck)
                    .addGroup(depPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(depParentLabel)
                        .addComponent(depParentField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depJavaLibsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depModsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(depPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(depMavenRepsPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depManifestPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        modPropertyTabs.addTab("Dependencies", depPanel);

        intellijRadButton.setText("IntelliJ");
        intellijRadButton.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                intellijRadButtonStateChanged(evt);
            }
        });

        eclipseRadButton.setText("Eclipse");
        eclipseRadButton.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                eclipseRadButtonStateChanged(evt);
            }
        });

        gradleVersionLabel.setHorizontalAlignment(SwingConstants.TRAILING);
        gradleVersionLabel.setText("Gradle 3.14");

        javaVersionLabel.setHorizontalAlignment(SwingConstants.TRAILING);
        javaVersionLabel.setText("Java 9.232");

        modGenerateButton.setText("Generate");
        modGenerateButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                modGenerateButtonActionPerformed(evt);
            }
        });

        GroupLayout modGeneratePanelLayout = new GroupLayout(modGeneratePanel);
        modGeneratePanel.setLayout(modGeneratePanelLayout);
        modGeneratePanelLayout.setHorizontalGroup(modGeneratePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(modGeneratePanelLayout.createSequentialGroup()
                .addComponent(filler1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modGenerateButton, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filler2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        modGeneratePanelLayout.setVerticalGroup(modGeneratePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(filler2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filler1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(GroupLayout.Alignment.TRAILING, modGeneratePanelLayout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modGenerateButton)
                .addGap(15, 15, 15))
        );

        fileMenu.setText("File");

        menuItemNew.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_N, CTRLCMD));
        menuItemNew.setText("New");
        fileMenu.add(menuItemNew);

        menuItemOpen.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_O, CTRLCMD));
        menuItemOpen.setText("Open");
        fileMenu.add(menuItemOpen);

        menuItemSave.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, CTRLCMD));
        menuItemSave.setText("Save");
        fileMenu.add(menuItemSave);

        menuItemSaveAs.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, CTRLCMD | InputEvent.ALT_MASK));
        menuItemSaveAs.setText("Save As");
        fileMenu.add(menuItemSaveAs);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        menuItemCopy.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_C, CTRLCMD));
        menuItemCopy.setText("Copy");
        editMenu.add(menuItemCopy);

        menuItemCut.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_X, CTRLCMD));
        menuItemCut.setText("Cut");
        editMenu.add(menuItemCut);

        menuItemPaste.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_V, CTRLCMD));
        menuItemPaste.setText("Paste");
        editMenu.add(menuItemPaste);

        menuItemSelectAll.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, CTRLCMD));
        menuItemSelectAll.setText("Select All");
        editMenu.add(menuItemSelectAll);

        menuItemDeselect.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, CTRLCMD | InputEvent.ALT_MASK));
        menuItemDeselect.setText("Deselect");
        editMenu.add(menuItemDeselect);

        menuBar.add(editMenu);

        projectMenu.setText("Project");

        menuItemGenerate.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_G, CTRLCMD));
        menuItemGenerate.setText("Generate");
        projectMenu.add(menuItemGenerate);

        menuItemClean.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_BACK_SPACE, CTRLCMD | InputEvent.SHIFT_MASK));
        menuItemClean.setText("Clean");
        projectMenu.add(menuItemClean);

        menuItemCompileJar.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_G, CTRLCMD | InputEvent.SHIFT_MASK));
        menuItemCompileJar.setText("Compile Jar");
        projectMenu.add(menuItemCompileJar);

        menuBar.add(projectMenu);

        aboutMenu.setText("About");

        menuItemAboutSB.setText("About SulfurBox");
        aboutMenu.add(menuItemAboutSB);

        menuItemManual.setText("Manual");
        aboutMenu.add(menuItemManual);

        menuItemOnlineSupport.setText("Online Support");
        aboutMenu.add(menuItemOnlineSupport);

        menuItemCheckUpdates.setText("Check For Updates");
        aboutMenu.add(menuItemCheckUpdates);

        menuItemRequestRepo.setText("Request Maven Repo");
        menuItemRequestRepo.setToolTipText("Request to Add Maven Mod Repository");
        aboutMenu.add(menuItemRequestRepo);

        menuBar.add(aboutMenu);

        optionsMenu.setText("Options");

        lafMenu.setText("Look And Feel");
        optionsMenu.add(lafMenu);

        menuBar.add(optionsMenu);

        setJMenuBar(menuBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(modPropertyTabs)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(eclipseRadButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                            .addComponent(intellijRadButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modGeneratePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(gradleVersionLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(javaVersionLabel, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modPropertyTabs)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(modGeneratePanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eclipseRadButton)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(intellijRadButton)
                                .addGap(0, 7, Short.MAX_VALUE))))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gradleVersionLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(javaVersionLabel)
                        .addContainerGap())))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Events">

	private void modNameFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modNameFieldKeyReleased
		ValidationError error = currentProject.setModName(modNameField.getText());
		if (error.severity == 1) modNameField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modNameField.setBackground(warningTextFieldInputColor);
		else modNameField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modNameField.setToolTipText(error.message);
	}//GEN-LAST:event_modNameFieldKeyReleased

	private void modPackageFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modPackageFieldKeyReleased
		ValidationError error = currentProject.setPackageName(modPackageField.getText());
		if (error.severity == 1) modPackageField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modPackageField.setBackground(warningTextFieldInputColor);
		else modPackageField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modPackageField.setToolTipText(error.message);
	}//GEN-LAST:event_modPackageFieldKeyReleased

	private void modPackageMemberFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modPackageMemberFieldKeyReleased
		ValidationError error = currentProject.setPackageModuleName(modPackageMemberField.getText());
		if (error.severity == 1) modPackageMemberField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modPackageMemberField.setBackground(warningTextFieldInputColor);
		else modPackageMemberField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modPackageMemberField.setToolTipText(error.message);
	}//GEN-LAST:event_modPackageMemberFieldKeyReleased

	private void modVersionFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modVersionFieldKeyReleased
		ValidationError error = currentProject.setModVersion(modVersionField.getText());
		if (error.severity == 1) modVersionField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modVersionField.setBackground(warningTextFieldInputColor);
		else modVersionField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modVersionField.setToolTipText(error.message);
	}//GEN-LAST:event_modVersionFieldKeyReleased

	private void mcVersionSelectItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_mcVersionSelectItemStateChanged
		ValidationError error = currentProject.setMcVersion(mcVersionSelect.getSelectedItem().toString());
		if (error.severity == 1) mcVersionSelect.setBackground(invalidChoiceInputColor);
		if (error.severity == 0) mcVersionSelect.setBackground(warningChoiceInputColor);
		else mcVersionSelect.setBackground(UIManager.getDefaults().getColor("ComboBox.background"));
		mcVersionSelect.setToolTipText(error.message);
	}//GEN-LAST:event_mcVersionSelectItemStateChanged

	private void forgeVersionSelectItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_forgeVersionSelectItemStateChanged
		ValidationError error = currentProject.setForgeVersion(forgeVersionSelect.getSelectedItem().toString());
		if (error.severity == 1) forgeVersionSelect.setBackground(invalidChoiceInputColor);
		if (error.severity == 0) forgeVersionSelect.setBackground(warningChoiceInputColor);
		else forgeVersionSelect.setBackground(UIManager.getDefaults().getColor("ComboBox.background"));
		forgeVersionSelect.setToolTipText(error.message);
	}//GEN-LAST:event_forgeVersionSelectItemStateChanged

	private void modDescriptionFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modDescriptionFieldKeyReleased
		ValidationError error = currentProject.setDescription(modDescriptionField.getText());
		if (error.severity == 1) modDescriptionField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modDescriptionField.setBackground(warningTextFieldInputColor);
		else modDescriptionField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modDescriptionField.setToolTipText(error.message);
	}//GEN-LAST:event_modDescriptionFieldKeyReleased

	private void modHomePageHttpsSelectItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_modHomePageHttpsSelectItemStateChanged
		ValidationError error = currentProject.setHomepage(modHomePageHttpsSelect.getSelectedItem().toString() + modHomePageField.getText());
	}//GEN-LAST:event_modHomePageHttpsSelectItemStateChanged

	private void modHomePageFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modHomePageFieldKeyReleased
		ValidationError error = currentProject.setHomepage(modHomePageHttpsSelect.getSelectedItem().toString() + modHomePageField.getText());
		if (error.severity == 1) modHomePageField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modHomePageField.setBackground(warningTextFieldInputColor);
		else modHomePageField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modHomePageField.setToolTipText(error.message);
	}//GEN-LAST:event_modHomePageFieldKeyReleased

	private void modRepoFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modRepoFieldKeyReleased
		ValidationError error = currentProject.setModRepository(modRepoField.getText());
		if (error.severity == 1) modRepoField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modRepoField.setBackground(warningTextFieldInputColor);
		else modRepoField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modRepoField.setToolTipText(error.message);
	}//GEN-LAST:event_modRepoFieldKeyReleased

	private void issueTrackerFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_issueTrackerFieldKeyReleased
		ValidationError error = currentProject.setIssuesPage(issueTrackerField.getText());
		if (error.severity == 1) issueTrackerField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) issueTrackerField.setBackground(warningTextFieldInputColor);
		else issueTrackerField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		issueTrackerField.setToolTipText(error.message);
	}//GEN-LAST:event_issueTrackerFieldKeyReleased

	private void modUpdateChecksFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modUpdateChecksFieldKeyReleased
		ValidationError error = currentProject.setUpdateCheck(modUpdateChecksField.getText());
		if (error.severity == 1) modUpdateChecksField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modUpdateChecksField.setBackground(warningTextFieldInputColor);
		else modUpdateChecksField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modUpdateChecksField.setToolTipText(error.message);
	}//GEN-LAST:event_modUpdateChecksFieldKeyReleased

	private void modCurseIDFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modCurseIDFieldKeyReleased
		ValidationError error = currentProject.setCurseForgeID(modCurseIDField.getText());
		if (error.severity == 1) modCurseIDField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modCurseIDField.setBackground(warningTextFieldInputColor);
		else modCurseIDField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modCurseIDField.setToolTipText(error.message);
	}//GEN-LAST:event_modCurseIDFieldKeyReleased

	private void modLicenseFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modLicenseFieldKeyReleased
		ValidationError error = currentProject.setLicense(modLicenseField.getSelectedItem().toString());
		if (error.severity == 1) modLicenseField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modLicenseField.setBackground(warningTextFieldInputColor);
		else modLicenseField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modLicenseField.setToolTipText(error.message);
	}//GEN-LAST:event_modLicenseFieldKeyReleased

	private void modLicenseFieldItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_modLicenseFieldItemStateChanged
		ValidationError error = currentProject.setLicense(modLicenseField.getSelectedItem().toString());
		if (error.severity == 1) modLicenseField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modLicenseField.setBackground(warningTextFieldInputColor);
		else modLicenseField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modLicenseField.setToolTipText(error.message);
	}//GEN-LAST:event_modLicenseFieldItemStateChanged

	private void modLogoFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_modLogoFieldKeyReleased
		ValidationError error = currentProject.setLogopath(modLogoField.getText());
		if (error.severity == 1) modLogoField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) modLogoField.setBackground(warningTextFieldInputColor);
		else modLogoField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		modLogoField.setToolTipText(error.message);
	}//GEN-LAST:event_modLogoFieldKeyReleased

	private void modLogoBrowseButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_modLogoBrowseButtonActionPerformed
		// TODO: Create me!
	}//GEN-LAST:event_modLogoBrowseButtonActionPerformed

	private void eclipseRadButtonStateChanged(ChangeEvent evt) {//GEN-FIRST:event_eclipseRadButtonStateChanged
		// TODO: Create me!
	}//GEN-LAST:event_eclipseRadButtonStateChanged

	private void intellijRadButtonStateChanged(ChangeEvent evt) {//GEN-FIRST:event_intellijRadButtonStateChanged
		// TODO: Create me!
	}//GEN-LAST:event_intellijRadButtonStateChanged

	private void modGenerateButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_modGenerateButtonActionPerformed
		// TODO: Create me!
		GenerateAll.construct(currentProject.project);
		if (eclipseRadButton.isSelected()) GenerateAll.generateIDE(currentProject.project, "eclipse");
		if (intellijRadButton.isSelected()) GenerateAll.generateIDE(currentProject.project, "idea");
	}//GEN-LAST:event_modGenerateButtonActionPerformed

	private void attribContributorTableKeyReleased(KeyEvent evt) {//GEN-FIRST:event_attribContributorTableKeyReleased
		// TODO: Create me!
	}//GEN-LAST:event_attribContributorTableKeyReleased

	private void attribContributorAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_attribContributorAddActionPerformed
		currentProject.addAuthor(new Author());
        reloadTables();

	}//GEN-LAST:event_attribContributorAddActionPerformed

	private void attribContributorRemoveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_attribContributorRemoveActionPerformed
		int selected = getSelectedRow(attribContributorTable);
        if (selected == -1) {
            return;
        }

        currentProject.delAuthor(selected);
        reloadTables();
	}//GEN-LAST:event_attribContributorRemoveActionPerformed

	private void attribCreditsFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_attribCreditsFieldKeyReleased
		ValidationError error = currentProject.setCredits(attribCreditsField.getText());
		if (error.severity == 1) attribCreditsField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) attribCreditsField.setBackground(warningTextFieldInputColor);
		else attribCreditsField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		attribCreditsField.setToolTipText(error.message);
	}//GEN-LAST:event_attribCreditsFieldKeyReleased

	private void depParentCheckStateChanged(ChangeEvent evt) {//GEN-FIRST:event_depParentCheckStateChanged
		// TODO: Create me!
	}//GEN-LAST:event_depParentCheckStateChanged

	private void depParentFieldKeyReleased(KeyEvent evt) {//GEN-FIRST:event_depParentFieldKeyReleased
		ValidationError error = currentProject.setParentMod(depParentField.getText());
		if (error.severity == 1) depParentField.setBackground(invalidTextFieldInputColor);
		if (error.severity == 0) depParentField.setBackground(warningTextFieldInputColor);
		else depParentField.setBackground(UIManager.getDefaults().getColor("TextField.background"));
		depParentField.setToolTipText(error.message);
	}//GEN-LAST:event_depParentFieldKeyReleased

	private void depModsTableKeyReleased(KeyEvent evt) {//GEN-FIRST:event_depModsTableKeyReleased
		// TODO: Create me!
	}//GEN-LAST:event_depModsTableKeyReleased

	private void depModsAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depModsAddActionPerformed
		currentProject.addDependency(new Dependency());
        reloadTables();

	}//GEN-LAST:event_depModsAddActionPerformed

	private void depModsRemoveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depModsRemoveActionPerformed
        int selected = getSelectedRow(depModsTable);
        if (selected == -1) {
            return;
        }

        currentProject.delDependency(selected);
        reloadTables();
	}//GEN-LAST:event_depModsRemoveActionPerformed

	private void depJavaLibsAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depJavaLibsAddActionPerformed
		currentProject.addJavaDependency(new Dependency());
        reloadTables();

	}//GEN-LAST:event_depJavaLibsAddActionPerformed

	private void depJavaLibsRemoveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depJavaLibsRemoveActionPerformed
        int selected = getSelectedRow(depJavaLibsTable);
        if (selected == -1) {
            return;
        }

        currentProject.delJavaDependency(selected);
        reloadTables();
	}//GEN-LAST:event_depJavaLibsRemoveActionPerformed

	private void depMavenRepsAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depMavenRepsAddActionPerformed
		currentProject.addMavenRepository(new MavenRepository());
        reloadTables();

	}//GEN-LAST:event_depMavenRepsAddActionPerformed

	private void depMavenRepsRemoveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depMavenRepsRemoveActionPerformed
        int selected = getSelectedRow(depMavenRepsTable);
        if (selected == -1) {
            return;
        }

        currentProject.delMavenRepository(selected);
        reloadTables();
	}//GEN-LAST:event_depMavenRepsRemoveActionPerformed

	private void depManifestAddActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depManifestAddActionPerformed
		currentProject.addManifestAttribute(new ManifestAttribute());
        reloadTables();

	}//GEN-LAST:event_depManifestAddActionPerformed

	private void depManifestRemoveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_depManifestRemoveActionPerformed
        int selected = getSelectedRow(depManifestTable);
        if (selected == -1) {
            return;
        }

        currentProject.delManifestAttribute((String) depManifestTableModel.getValueAt(selected, 0));
        reloadTables();
	}//GEN-LAST:event_depManifestRemoveActionPerformed

    private void depJavaLibsTableKeyReleased(KeyEvent evt) {//GEN-FIRST:event_depJavaLibsTableKeyReleased
        // TODO: Create me!
    }//GEN-LAST:event_depJavaLibsTableKeyReleased

    private void depManifestTableKeyReleased(KeyEvent evt) {//GEN-FIRST:event_depManifestTableKeyReleased
        // TODO: Create me!
    }//GEN-LAST:event_depManifestTableKeyReleased

    private void depMavenRepsTableKeyReleased(KeyEvent evt) {//GEN-FIRST:event_depMavenRepsTableKeyReleased
        // TODO: Create me!
    }//GEN-LAST:event_depMavenRepsTableKeyReleased

    //</editor-fold>

    //<editor-fold defaultstate="collapsed" desc="List Handlers">

    private void initTablesListeners() {
        contribTableModel.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();
            if (e.getType() != TableModelEvent.UPDATE || row == -1 || column == -1) {
                return;
            }

            Object value = contribTableModel.getValueAt(row, column);
            Author author = currentProject.getAuthor(row);
            switch (e.getColumn()) {
                case 1: author.username = (String) value; break;
                case 2: author.userid = (String) value; break;
                case 3: author.role = (String) value; break;
            }

            reloadTables();
        });

        depModsTableModel.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();
            if (e.getType() != TableModelEvent.UPDATE || row == -1 || column == -1) {
                return;
            }

            Object value = depModsTableModel.getValueAt(row, column);
            Dependency dep = currentProject.getDependency(row);
            switch (e.getColumn()) {
                case 0: dep.depName = (String) value; break;
                case 1: dep.depVersion = new Version((String) value); break;
                case 2: dep.disallowHigherVersion = (Boolean) value; break;
            }

            reloadTables();
        });

        depJavaLibsTableModel.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();
            if (e.getType() != TableModelEvent.UPDATE || row == -1 || column == -1) {
                return;
            }

            Object value = depJavaLibsTableModel.getValueAt(row, column);
            Dependency dep = currentProject.getJavaDependency(row);
            switch (e.getColumn()) {
                case 0: dep.depName = (String) value; break;
                case 1: dep.depVersion = new Version((String) value); break;
                case 2: dep.disallowHigherVersion = (Boolean) value; break;
            }

            reloadTables();
        });

        depMavenRepsTableModel.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();
            if (e.getType() != TableModelEvent.UPDATE || row == -1 || column == -1) {
                return;
            }

            Object value = depMavenRepsTableModel.getValueAt(row, column);
            MavenRepository repo = currentProject.getMavenRepository(row);
            switch (e.getColumn()) {
                case 0: repo.name = (String) value; break;
                case 1: repo.url = (String) value; break;
            }

            reloadTables();
        });

        depManifestTableModel.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();
            if (e.getType() != TableModelEvent.UPDATE || row == -1 || column == -1) {
                return;
            }

            String tableKey = (String) depManifestTableModel.getValueAt(row, 0);
            String tableValue = (String) depManifestTableModel.getValueAt(row, 1);
            Map<String, String> attribs = currentProject.getManifestAttributes().getAttributes();

            //Not sure if this is the best way to get a map key by its index in the map.
            String targetKey = Lists.newArrayList(attribs.keySet()).get(row);

            attribs.remove(targetKey);
            attribs.put(tableKey, tableValue);
            System.out.println(tableValue);

            reloadTables();
        });
    }

    public void reloadTables() {
        //Reload Contributor table
        clearTable(contribTableModel);
        for (Author author : currentProject.getAuthors()) {
            contribTableModel.addRow(new Object[] {"", author.username, author.userid, author.role});
        }

        //Reload the mod deps table
        clearTable(depModsTableModel);
        for (Dependency dep : currentProject.getDependencies()) {
            depModsTableModel.addRow(new Object[] {dep.depName, dep.depVersion, dep.disallowHigherVersion});
        }

        //Reload the java Libs table
        clearTable(depJavaLibsTableModel);
        for (Dependency dep : currentProject.getJavaDependencies()) {
            depJavaLibsTableModel.addRow(new Object[] {dep.depName, dep.depVersion, dep.disallowHigherVersion});
        }

        //Reload the Maven Repo table
        clearTable(depMavenRepsTableModel);
        for (MavenRepository repo : currentProject.getMavenRepositories()) {
            depMavenRepsTableModel.addRow(new Object[] {repo.name, repo.url});
        }

        //Reload the Manifest table
        clearTable(depManifestTableModel);
        for (Map.Entry<String, String> entry : currentProject.getManifestAttributes().getAttributes().entrySet()) {
            depManifestTableModel.addRow(new Object[] {entry.getKey(), entry.getValue()});
        }
    }

    private void clearTable(DefaultTableModel tableModel) {
        while (tableModel.getRowCount() > 0) {
            tableModel.removeRow(0);
        }
    }

    private int getSelectedRow(JTable table) {
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "No row selected!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return row;
    }

    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenu aboutMenu;
    private JButton attribContributorAdd;
    private JButton attribContributorRemove;
    private JScrollPane attribContributorScrlPane;
    private JTable attribContributorTable;
    private DefaultTableModel contribTableModel;
    private JTextArea attribCreditsField;
    private JLabel attribCreditsLabel;
    private JScrollPane attribCreditsScrlPane;
    private JPanel attribPanel;
    private JButton depJavaLibsAdd;
    private JLabel depJavaLibsFields;
    private JPanel depJavaLibsPanel;
    private JButton depJavaLibsRemove;
    private JTable depJavaLibsTable;
    private DefaultTableModel depJavaLibsTableModel;
    private JButton depManifestAdd;
    private JLabel depManifestLabel;
    private JPanel depManifestPanel;
    private JButton depManifestRemove;
    private JTable depManifestTable;
    private DefaultTableModel depManifestTableModel;
    private JButton depMavenRepsAdd;
    private JLabel depMavenRepsLabel;
    private JPanel depMavenRepsPanel;
    private JButton depMavenRepsRemove;
    private JTable depMavenRepsTable;
    private DefaultTableModel depMavenRepsTableModel;
    private JButton depModsAdd;
    private JLabel depModsLabel;
    private JPanel depModsPanel;
    private JButton depModsRemove;
    private JScrollPane depModsScrlPane;
    private JScrollPane depModsScrlPane1;
    private JScrollPane depModsScrlPane2;
    private JScrollPane depModsScrlPane3;
    private JTable depModsTable;
    private DefaultTableModel depModsTableModel;
    private JPanel depPanel;
    private JCheckBox depParentCheck;
    private JTextField depParentField;
    private JLabel depParentLabel;
    private JRadioButton eclipseRadButton;
    private JMenu editMenu;
    private JMenu fileMenu;
    private Box.Filler filler1;
    private Box.Filler filler2;
    private JComboBox<String> forgeVersionSelect;
    private JLabel gradleVersionLabel;
    private JRadioButton intellijRadButton;
    private JTextField issueTrackerField;
    private JLabel issueTrackerLabel;
    private JLabel javaVersionLabel;
    private JMenu lafMenu;
    private JLabel mcForgeVersionLabel;
    private JComboBox<String> mcVersionSelect;
    private JMenuBar menuBar;
    private JMenuItem menuItemAboutSB;
    private JMenuItem menuItemCheckUpdates;
    private JMenuItem menuItemClean;
    private JMenuItem menuItemCompileJar;
    private JMenuItem menuItemCopy;
    private JMenuItem menuItemCut;
    private JMenuItem menuItemDeselect;
    private JMenuItem menuItemGenerate;
    private JMenuItem menuItemManual;
    private JMenuItem menuItemNew;
    private JMenuItem menuItemOnlineSupport;
    private JMenuItem menuItemOpen;
    private JMenuItem menuItemPaste;
    private JMenuItem menuItemRequestRepo;
    private JMenuItem menuItemSave;
    private JMenuItem menuItemSaveAs;
    private JMenuItem menuItemSelectAll;
    private JTextField modCurseIDField;
    private JLabel modCurseIDLabel;
    private JTextArea modDescriptionField;
    private JLabel modDescriptionLabel;
    private JScrollPane modDescriptionScrlPane;
    private JButton modGenerateButton;
    private JPanel modGeneratePanel;
    private JTextField modHomePageField;
    private JComboBox<String> modHomePageHttpsSelect;
    private JLabel modHomePageLabel;
    private JComboBox<String> modLicenseField;
    private JLabel modLicenseLabel;
    private JButton modLogoBrowseButton;
    private JTextField modLogoField;
    private JLabel modLogoLabel;
    private JTextField modNameField;
    private JLabel modNameLabel;
    private JTextField modPackageField;
    private JLabel modPackageLabel;
    private JTextField modPackageMemberField;
    private JLabel modPackageSeparatorLabel;
    private JPanel modPanel;
    private JTabbedPane modPropertyTabs;
    private JTextField modRepoField;
    private JLabel modRepoLabel;
    private JTextField modUpdateChecksField;
    private JLabel modUpdateChecksLabel;
    private JTextField modVersionField;
    private JLabel modVersionLabel;
    private JMenu optionsMenu;
    private JMenu projectMenu;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
